apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketing-site
  labels:
    app: marketing-site
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: marketing-site
  template:
    metadata:
      labels:
        app: marketing-site
    spec:
      containers:
        - name: marketing-site
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
