apiVersion: apps/v1
kind: Deployment
metadata:
  name: trust-portal
  labels:
    app: trust-portal
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: trust-portal
  template:
    metadata:
      labels:
        app: trust-portal
    spec:
      containers:
        - name: trust-portal
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
