apiVersion: v1
kind: Service
metadata:
  name: trust-portal
  labels:
    app: trust-portal
spec:
  type: {{ .Values.service.type }}
  selector:
    app: trust-portal
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
