apiVersion: v1
kind: Service
metadata:
  name: intelligence
  labels:
    app: intelligence
spec:
  type: {{ .Values.service.type }}
  selector:
    app: intelligence
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
