apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-forms
  labels:
    app: compliance-forms
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: compliance-forms
  template:
    metadata:
      labels:
        app: compliance-forms
    spec:
      containers:
        - name: compliance-forms
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
