apiVersion: v1
kind: Service
metadata:
  name: compliance-forms
  labels:
    app: compliance-forms
spec:
  type: {{ .Values.service.type }}
  selector:
    app: compliance-forms
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
