apiVersion: v1
kind: Service
metadata:
  name: realtime-gateway
  labels:
    app: realtime-gateway
spec:
  type: {{ .Values.service.type }}
  selector:
    app: realtime-gateway
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
