apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintain
  labels:
    app: maintain
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: maintain
  template:
    metadata:
      labels:
        app: maintain
    spec:
      containers:
        - name: maintain
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
