apiVersion: v1
kind: Service
metadata:
  name: compliance
  labels:
    app: compliance
spec:
  type: {{ .Values.service.type }}
  selector:
    app: compliance
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
