apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-console
  labels:
    app: admin-console
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: admin-console
  template:
    metadata:
      labels:
        app: admin-console
    spec:
      containers:
        - name: admin-console
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
