apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-bridge
  labels:
    app: iot-bridge
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: iot-bridge
  template:
    metadata:
      labels:
        app: iot-bridge
    spec:
      containers:
        - name: iot-bridge
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
