apiVersion: v1
kind: Service
metadata:
  name: esg
  labels:
    app: esg
spec:
  type: {{ .Values.service.type }}
  selector:
    app: esg
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
