apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-pwa
  labels:
    app: ops-pwa
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ops-pwa
  template:
    metadata:
      labels:
        app: ops-pwa
    spec:
      containers:
        - name: ops-pwa
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
