apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-control
  labels:
    app: document-control
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: document-control
  template:
    metadata:
      labels:
        app: document-control
    spec:
      containers:
        - name: document-control
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
